[build]
builder = "nixpacks"
nixpkgsId = "nixpkgs-unstable"
buildCommand = "git lfs install && git lfs pull && npm ci && npm run build && npm run copy-public"

[build.nixpacks]
pkgs = ["git-lfs"]

[deploy]
startCommand = "node backend/server.js"
restartPolicyMaxRetries = 5
restartPolicyWindowMs = 60000
